function getPlayerNames(nicknames) {
  var assignedName = nicknames[Math.floor(Math.random() * nicknames.length)];
  return assignedName;
}

const funNicknames = [
  'MAChael Jackson',
  'Kat Stevens',
  'Christina AguiLaura',
  'A Tribe Called Kirstie',
  'AmanDaBaby',
  'LBeyonce',
  'Saylor Twift',
  'Bavid Dowie',
  'Lay-Z',
  'Bardi C',
  'Micki Ninaj',
  'Maaba Baal',
  'Werard Gay',
  'PlackBink',
  'Ved Relvet',
];

const professionalNicknames = [
  'Prince',
  'Taylor Swift',
  'Wolfgang Amadeus Mozart',
  'Elvis Presley',
  'Etta James',
  'Beyoncé',
  'Jimi Hendrix',
  'Ludwig van Beethoven',
  'Johnny Cash',
  'Jay-Z',
  'Red Velvet',
  'Aretha Franklin',
  'Gustav Mahler',
  'Cardi B',
  'Nicki Minaj',
  'Baaba Maal',
  'Cat Stevens',
  'Philip Glass',
  'Natalia Lafourcade',
  'Selena',
  'Hector Lavoe',
  'Luis Miguel',
  'Gerard Way',
  'Twice',
  'BlackPink',
  'Loona',
  'St. Vincent',
  'Shintaro Sakamoto',
  'Lil Nas X',
  'Fergie',
  'Johann Sebastian Bach',
  'The Beach Boys',
  'Daft Punk',
  'Brian Eno',
  'Girls Generation',
  '2NE1',
  'Lorde',
  'A Tribe Called Quest',
  'Michael Jackson',
  'Madonna',
  'Dua Lipa',
  'Doja Cat',
  'Ariana Grande',
  'J.Cole',
  'Kendrick Lamar',
  'Billie Eilish',
  'Mitski',
  'Bad Bunny',
  'Daddy Yankee',
  'SZA',
  'Sufjan Stevens',
  'Linkin Park',
  'Fall Out Boy',
  'Dolly Parton',
  'Childish Gambino',
  'Swamp Dogg',
  'Paul Simon',
  'Boots Riley',
  'Wesley Willis',
  'Evan Greer',
  'Jonathan Richman',
  'Jeff Mangum',
  'Suzanne Vega',
  'Lizzo',
  'Tina Turner',
];

module.exports = { getPlayerNames, professionalNicknames, funNicknames };
