export function getPlayerNames(nicknames) {
  var assignedName = nicknames[Math.floor(Math.random() * nicknames.length)];
  return assignedName;
}

export const funNicknames = [
  "MAChael Jackson",
  "Kat Stevens",
  "Christina AguiLaura",
  "A Tribe Called Kirstie",
  "AmanDaBaby",
  "LBeyonce",
  "Saylor Twift",
  "Bavid Dowie",
  "Lay-Z",
  "Bardi C",
  "Micki Ninaj",
  "Maaba Baal",
  "Werard Gay",
  "PlackBink",
  "Ved Relvet",
];

export const professionalNicknames = [
  "Prince",
  "Taylor Swift",
  "Wolfgang Amadeus Mozart",
  "Elvis Preley",
  "Etta James",
  "Beyoncé",
  "David Bowie",
  "Jimi Hendrix",
  "Ludwig van Beethoven",
  "Johnny Cash",
  "Jay-Z",
  "Red Velvet",
  "Aretha Franklin",
  "Gustav Mahler",
  "Cardi B",
  "Nicki Minaj",
  "Baaba Maal",
  "Cat Stevens",
  "Natalia Lafourcade",
  "Selena",
  "Hector Lavoe",
  "Luis Miguel",
  "Gerard Way",
  "Twice",
  "BlackPink",
  "Loona",
  "St. Vincent",
  "Shintaro Sakamoto",
  "Lil Nas X",
  "Fergie",
  "Johann Sebastian Bach",
  "The Beach Boys",
  "Daft Punk",
  "Brian Eno",
  "Girls Generation",
  "2NE1",
  "Lorde",
  "A Tribe Called Quest",
  "Michael Jackson",
  "Madonna",
  "Dua Lipa",
  "Doja Cat",
  "Ariana Grande",
  "J.Cole",
  "Kendrick Lamar",
  "Billie Eilish",
  "Mitski",
  "Bad Bunny",
  "Daddy Yankee",
  "SZA",
  "Linkin Park",
  "Fall Out Boy",
  "Dolly Parton",
];
